# Git Hub Actions new comment new role
on:
  push:
    branches:
      - push_iot
name: deploy greengrass component
jobs:
  deploy:
    name: deploy to IoT greengrass
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-west-1
    - name: Aws configure list
      run: sudo aws configure list
    - name: Install GDK
      run: sudo python3 -m pip install -U git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git@v1.1.0
    - name: Build GDK
      run: sudo gdk component build
    - name: Publish GDK
      run: sudo gdk component publish
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  
